### PR TITLE
Add macOS-10.14

### PR DESCRIPTION
**Pull request by lrapetti**
Adding the compilation of dependencies for `MacOS 10.14`

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
Just a curiosity, why is this required? Can we drop `macos-latest`?

**Comment by lrapetti** [comment]
> Just a curiosity, why is this required? Can we drop `macos-latest`?

I think we can drop it, at least for the time being none is going to use it.

**Comment by lrapetti** [comment]
All checks seems to be completed even if actually the `MacOS 10.14` is not supported, and the following warning is raised:
```
The macOS virtual environment has been updated to Catalina (v10.15). Please update your workflow and change the line 'runs-on: macOS-10.14' to 'runs-on: macOS-latest'
```
so probably it updated by itself the OS to 10.15

**Comment by lrapetti** [comment]
> so probably it updated by itself the OS to 10.15

I just checked and I confirm it switch to `10.15` by itself. 

Screenshot 2020-06-18 at 16 57 15


In addiction, you can see that before [removing `macOS-latest`](https://github.com/dic-iit/ify-dependencies-vcpkg/pull/9/commits/d97eb881daf17acb8683dbadcf422471faf2d4f0) the job on `macOS-10.14` was instead failing: https://github.com/dic-iit/ify-dependencies-vcpkg/runs/783622814

**Comment by lrapetti** [comment]
Closing since it is not possible to add `macOS-10.14`, we should investigate another way to generate the dependencies.

**Pull request closed without merging**
