### PR TITLE
Enable macOS vcpkg triples compilation

### PR DESCRIPTION
**Pull request by GiulioRomualdi**

### CODE REVIEW

**Comment by traversaro** [comment]
Actually the reason why the CI was not starting was a `.yml` syntax error... sorry for the noise.

**Comment by GiulioRomualdi** [comment]
Unfortunately adding osx the compilation time, for windows, lasts more than 6 hours.

**Comment by traversaro** [comment]
> 
> 
> Unfortunately adding osx the compilation time, for windows, lasts more than 6 hours.

That is quite strange, the `osx` build should not influence the Windows build.

**Comment by traversaro** [comment]
> 
> 
> > Unfortunately adding osx the compilation time, for windows, lasts more than 6 hours.
> 
> That is quite strange, the `osx` build should not influence the Windows build.

The actual error seems to be: 
~~~
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/ify-deps/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "panama -Sy --noconfirm --needed make automake1.15"
    Working Directory: C:/ify-deps/vcpkg/downloads/tools/msys2
    Error code: Access violation
    See logs for more information:
      C:\ify-deps\vcpkg\buildtrees\icu\msys-pacman-x64-windows-static-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:77 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)
~~~
and then the builds hangs there. I suspect we have the same errors without modifications  (I opened https://github.com/dic-iit/ify-dependencies-vcpkg/pull/4 to check this). 

I saw a lot of `msys2` related issues and PRs lately in vcpkg, so I think that using a recent vcpkg commit (one after https://github.com/microsoft/vcpkg/pull/11443) should work fine. 
Note that probably it make sense to add a scheduled job to GitHub actions so we realize this environment failures before we try to do unrelated changes.

**Comment by GiulioRomualdi** [comment]
We may try to use the latest commit: https://github.com/microsoft/vcpkg/commit/6d36e2a86baf8d227fc6dce587bd69997d67fb5e

**Comment by GiulioRomualdi** [comment]
If you agree I can create the release `v0.3.0`

**Comment by traversaro** [comment]
> 
> 
> If you agree I can create the release `v0.3.0`

Absolutely yes!

**Pull request merged**
