### PR TITLE
Add the linux triplet in ci.yml

### PR DESCRIPTION
**Pull request by GiulioRomualdi**

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
The job is failing with:
```
-- Downloading https://github.com/google/angle/archive/d949154da428bb3e924e28a8eadfe2327631c8bb.tar.gz...
-- Extracting source /ify-deps/vcpkg/downloads/google-angle-d949154da428bb3e924e28a8eadfe2327631c8bb.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Using source at /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /ify-deps/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /ify-deps/vcpkg/buildtrees/angle/x64-linux-dbg
    See logs for more information:
      /ify-deps/vcpkg/buildtrees/angle/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:41 (vcpkg_install_cmake)
  scripts/ports.cmake:90 (include)


Error: Building package angle:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: angle:x64-linux
  Vcpkg version: 2020.02.04-unknownhash
```

I am able to reproduce the error in a clean docker image. I'm investigating on it

**Comment by GiulioRomualdi** [comment]
This is the error 
```
[1/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/PackedEnums.cpp.o -MF CMakeFiles/angle_common.dir/src/common/PackedEnums.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/PackedEnums.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEnums.cpp
FAILED: CMakeFiles/angle_common.dir/src/common/PackedEnums.cpp.o 
/usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/PackedEnums.cpp.o -MF CMakeFiles/angle_common.dir/src/common/PackedEnums.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/PackedEnums.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEnums.cpp
In file included from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/egl.h:39:0,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEGLEnums_autogen.h:15,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEnums.h:12,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEnums.cpp:9:
/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/eglplatform.h:128:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
[2/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/PackedGLEnums_autogen.cpp.o -MF CMakeFiles/angle_common.dir/src/common/PackedGLEnums_autogen.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/PackedGLEnums_autogen.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedGLEnums_autogen.cpp
FAILED: CMakeFiles/angle_common.dir/src/common/PackedGLEnums_autogen.cpp.o 
/usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/PackedGLEnums_autogen.cpp.o -MF CMakeFiles/angle_common.dir/src/common/PackedGLEnums_autogen.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/PackedGLEnums_autogen.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedGLEnums_autogen.cpp
In file included from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/egl.h:39:0,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedGLEnums_autogen.h:15,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedGLEnums_autogen.cpp:12:
/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/eglplatform.h:128:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
[3/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/PackedEGLEnums_autogen.cpp.o -MF CMakeFiles/angle_common.dir/src/common/PackedEGLEnums_autogen.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/PackedEGLEnums_autogen.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEGLEnums_autogen.cpp
FAILED: CMakeFiles/angle_common.dir/src/common/PackedEGLEnums_autogen.cpp.o 
/usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/PackedEGLEnums_autogen.cpp.o -MF CMakeFiles/angle_common.dir/src/common/PackedEGLEnums_autogen.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/PackedEGLEnums_autogen.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEGLEnums_autogen.cpp
In file included from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/egl.h:39:0,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEGLEnums_autogen.h:15,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PackedEGLEnums_autogen.cpp:12:
/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/eglplatform.h:128:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
[4/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/android_util.cpp.o -MF CMakeFiles/angle_common.dir/src/common/android_util.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/android_util.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/android_util.cpp
FAILED: CMakeFiles/angle_common.dir/src/common/android_util.cpp.o 
/usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/android_util.cpp.o -MF CMakeFiles/angle_common.dir/src/common/android_util.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/android_util.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/android_util.cpp
In file included from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/egl.h:39:0,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/android_util.h:12,
                 from /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/android_util.cpp:9:
/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include/EGL/eglplatform.h:128:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
[5/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_ENABLE_NULL -DANGLE_ENABLE_OPENGL -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_USE_X11 -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DLIBANGLE_IMPLEMENTATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/third_party/khronos -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/libANGLE.dir/src/libANGLE/gl_enum_utils.cpp.o -MF CMakeFiles/libANGLE.dir/src/libANGLE/gl_enum_utils.cpp.o.d -o CMakeFiles/libANGLE.dir/src/libANGLE/gl_enum_utils.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/libANGLE/gl_enum_utils.cpp
[6/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/MemoryBuffer.cpp.o -MF CMakeFiles/angle_common.dir/src/common/MemoryBuffer.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/MemoryBuffer.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/MemoryBuffer.cpp
[7/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/Float16ToFloat32.cpp.o -MF CMakeFiles/angle_common.dir/src/common/Float16ToFloat32.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/Float16ToFloat32.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/Float16ToFloat32.cpp
[8/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/angleutils.cpp.o -MF CMakeFiles/angle_common.dir/src/common/angleutils.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/angleutils.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/angleutils.cpp
[9/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/aligned_memory.cpp.o -MF CMakeFiles/angle_common.dir/src/common/aligned_memory.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/aligned_memory.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/aligned_memory.cpp
[10/350] /usr/bin/c++  -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DANGLE_EXPORT="" -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DGL_API="" -DGL_APICALL="" -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/include -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src -Iinclude -I/ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/third_party/base -fPIC -g -fPIC   -std=gnu++1z -MD -MT CMakeFiles/angle_common.dir/src/common/PoolAlloc.cpp.o -MF CMakeFiles/angle_common.dir/src/common/PoolAlloc.cpp.o.d -o CMakeFiles/angle_common.dir/src/common/PoolAlloc.cpp.o -c /ify-deps/vcpkg/buildtrees/angle/src/327631c8bb-4828ad6d2c/src/common/PoolAlloc.cpp
ninja: build stopped: subcommand failed.
```

Installing `libx11-dev` solves the problem

**Comment by traversaro** [comment]
Related vcpkg issue; https://github.com/microsoft/vcpkg/issues/11727 .

**Comment by GiulioRomualdi** [comment]
Actually now the job is failing because of lack of space

image

**Comment by GiulioRomualdi** [comment]
@traversaro any Idea? Otherwise we may drop the PR

**Comment by traversaro** [comment]
> @traversaro any Idea? Otherwise we may drop the PR

I  had similar problems on Windows, the strategy that I used back in time were: 
* Check if there is another drive with more space with `df -h` 
* Delete all the unused stuff (see https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/pull/5/files#diff-e9f950f17198d3d5e3122a44230a09b9R19)
* Install some ports, remove the buildtrees, and then install the other ports 

However, we can also just close the issue at all.

**Comment by GiulioRomualdi** [comment]
This is the amount of space available on **ubuntu**
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           693M  960K  692M   1% /run
/dev/sdb1        84G   68G   16G  81% /
tmpfs           3.4G  8.0K  3.4G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/loop0       40M   40M     0 100% /snap/hub/43
/dev/loop1       94M   94M     0 100% /snap/core/9066
/dev/sdb15      105M  3.6M  101M   4% /boot/efi
/dev/sda1        14G   41M   13G   1% /mnt
/dev/loop2       98M   98M     0 100% /snap/core/9289
```
while on **macOS** 
```
df -h
Filesystem      Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5   380Gi   10Gi  226Gi     5%  487347 3982053053    0%   /
devfs          184Ki  184Ki    0Bi   100%     636          0  100%   /dev
/dev/disk1s1   380Gi  143Gi  226Gi    39% 4273968 3978266432    0%   /System/Volumes/Data
/dev/disk1s4   380Gi  1.0Mi  226Gi     1%       1 3982540399    0%   /private/var/vm
map auto_home    0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
```

**Comment by GiulioRomualdi** [comment]
In https://github.com/vmware-tanzu/antrea/commit/001289dfaa2295c11671806345b46a697d4aff20 they add run `apt-get clean` for removing useless files.

**Comment by GiulioRomualdi** [comment]
We are almost there. ` qt5-tools` is not compiling.
```
Error: Building package qt5-tools:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-tools:x64-linux
  Vcpkg version: 2020.02.04-unknownhash
```

I tried to replicate the experiment in a clean docker image. Unfortunately, I don't have enough free space of the disk to replicate the error

**Comment by traversaro** [comment]
>

**Comment by GiulioRomualdi** [comment]
I'm working on this. 
1. I ran in a clean docker image the following command:
   ```sh
   ./ify-deps/vcpkg/vcpkg install --triplet x64-linux catch2 qt5-base[latest] qt5-serialport
   ```
   (notice `qt5-tool` is missing)
2. Then I checked the space required 
   ```
   du -sh /ify-deps/vcpkg
   20G	/ify-deps/vcpkg
   ```
3. I removed useless folders 
   ```sh
    rm -rf ./ify-deps/vcpkg/buildtrees
    rm -rf ./ify-deps/vcpkg/packages
    rm -rf ./ify-deps/vcpkg/downloads
    du -sh /ify-deps/vcpkg
    3.8G	/ify-deps/vcpkg
   ```
    as far as I understood this is already too large https://github.com/dic-iit/ify-dependencies-vcpkg/issues/7 @S-Dafarra @traversaro 
4. I ran 
    ```sh
    ./ify-deps/vcpkg/vcpkg install --triplet x64-linux qt5-tools
    ```
   ... work in progress

**Comment by traversaro** [comment]
>  as far as I understood this is already too large #7 @S-Dafarra @traversaro

The 2 Gb limits is after  compression.

**Comment by GiulioRomualdi** [comment]
Following the instruction depicted in https://github.com/dic-iit/ify-dependencies-vcpkg/pull/5#issuecomment-644753650, I was able to compile `qt5-tools`. I can try to replicate it in the GitHub Action

**Comment by GiulioRomualdi** [comment]
Since I'm not working on this task I would close this PR without merging.If it's required in the future we can reopen it  again

**Pull request closed without merging**
